Fixes 26 - Adds config file creation logic in case it doesn't exist
apimatic/apimatic-cli pull request #27
Opened 2021-11-17 06:51 UTC by harishasan

2021-11-17 17:07 UTC, safeerraees requested changes

2021-11-17 17:07 UTC, safeerraees commented on src/client-utils/auth-manager.ts
> +  return await fs.writeFile(configFilePath, JSON.stringify(credentials));
Instead of checking file exists we can use the "w" flag option of the writeFile function to create the file if it doesn't exist. Although, it is default in Nodejs documentation, we might need to investigate why the default flag is not working
Reference:  
https://nodejs.org/api/fs.html#fs_file_system_flags

![image](https://user-images.githubusercontent.com/45023860/142173481-a48487ae-f470-4e34-8a44-614654dfac16.png)
![image](https://user-images.githubusercontent.com/45023860/142174010-1f9d0871-d6b5-4e5d-8c7a-5c8d7f413c3b.png)

2021-11-18 06:17 UTC, harishasan commented on src/client-utils/auth-manager.ts
> +  return await fs.writeFile(configFilePath, JSON.stringify(credentials));
@safeerraees this is the reason it is failing https://stackoverflow.com/a/50927704

So we can also do 
```
await mkdirp(configDir);
return await fs.writeFile(path.join(configDir, "config.json"), JSON.stringify(credentials), { flag: "w" });
```

Your call however you want to do this.

2021-11-18 12:01 UTC, safeerraees approved these changes

2021-11-18 12:04 UTC, merged